### ISSUE TITLE
Mejora visual en los lotes

### ISSUE THREAD

**Issue by JuniorCorzo** [JuniorCorzo/Dayen#59]
Entre El titulo lote y donde estan los lotes hay un cambio bastante fuerte por favor añadir una especie de lina de por medio que diferencie o algo a su criterio que mejor eso

![Screenshot from 2024-03-27 23-14-00](https://github.com/JuniorCorzo/Dayen/assets/82859559/0ec9f55d-556b-4373-bc3a-ed3446603ffb)

**Comment by Yesica11** [comment]
ahi estaban mis botones jajajjajajaj
